services:
  nextjs:
    command: npm run dev
    depends_on:
      - apollo
    image: node:22-bullseye
    ports:
      - 3000:3000
    restart: always
    user: node
    volumes:
      - .:/app
    working_dir: /app

  apollo:
    build:
      context: ./apps/apollo
    ports:
      - 4000:4000
